version: '3.7'

services:
  web:
    build: ./pruebaFlinkapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pruebaFlinkapp/:/usr/src/pruebaFlinkapp/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user_dev

volumes:
  postgres_data:
