# Generated by Django 4.0.2 on 2022-02-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='valores',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='simbolo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
