# Generated by Django 4.0.2 on 2022-02-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_valores_alter_empresa_simbolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='valores',
            field=models.CharField(default='', max_length=300),
        ),
    ]
