# Generated by Django 4.0.2 on 2022-02-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_valores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='valores',
            field=models.CharField(default='', max_length=400),
        ),
    ]
